pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path("", views.index, name="index")
    # path("", views.index, {'pagename': ''}, name="home"), --Modified to following line
    path("", views.index, name="home"),
    path("contact", views.contact, name="contact"),
    path("<str:pagename>", views.index, name="index"),
]

project_files/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quote/', include('quotes.urls')),
    path("", include('pages.urls')),
]

quotes/urls.py
from django.urls import path

from . import views
from .views import QuoteList, QuoteView

urlpatterns = [
    path('', views.quote_req, name='quote-request'),
    path('show/<int:pk>', QuoteView.as_view(), name='quote-detail'),
    path('show', QuoteList.as_view(), name='show-quotes'),
]

pages/models.py
from django.db import models

class Page(models.Model):
    title = models.CharField(max_length=60)
    permalink = models.CharField(max_length=12, unique=True)
    update_date = models.DateTimeField('Last Updated')
    bodytext = models.TextField('Page Content', blank=True)

    def __str__(self):
        return self.title
    

quotes/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICES = (
    ('NEW', 'New Site'),
    ('EX', 'Existing Site'),
)

PRIORITY_CHOICES = (
    ('U', 'Urgent - 1 week or less'),
    ('N', 'Normal - 2 to 4 weeks'),
    ('L', 'Low - Still Researching'),
)

class Quote(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=60, blank=True)
    company = models.CharField(max_length=60, blank=True)
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    email = models.EmailField()
    web = models.URLField(blank=True)
    description = models.TextField()
    sitestatus = models.CharField(max_length=20, choices=STATUS_CHOICES)
    priority = models.CharField(max_length=40, choices=PRIORITY_CHOICES)
    jobfile = models.FileField(upload_to='uploads/', blank=True)
    submitted = models.DateField(auto_now_add=True)
    quotedate = models.DateField(blank=True, null=True)
    quoteprice = models.DecimalField(max_digits=7, decimal_places=2, blank=True, default=0)
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)


    def __str__(self):
        return str(self.id)
    

pages/forms.py
from django import forms


class ContactForm(forms.Form):
    yourname = forms.CharField(max_length=100, label='Your Name')
    email = forms.EmailField(required=False, label="Your E-mail Address")
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

quotes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Quote

class QuoteForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Quote
        fields = [
            'name', 'position', 'company', 'address', 'phone', 
            'email', 'web', 'description', 'sitestatus', 
            'priority', 'jobfile'
        ]

pages/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, get_connection

from . models import Page
from . forms import ContactForm


# def index(request):
def index(request, pagename=''):
    pagename = '/' + pagename
    pg = get_object_or_404(Page, permalink=pagename)
    context = {
        'title': pg.title,
        'content': pg.bodytext,
        'last_updated': pg.update_date,
        'page_list': Page.objects.all(),
    }
    # assert False
    return render(request, 'pages/page.html', context)


def contact(request):
    submitted = False

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # assert False
            # Send an email to the server administrator
            conn = get_connection(
                'django.core.mail.backends.console.EmailBackend')
            send_mail(cd['subject'], cd['message'], cd.get(
                'email', 'noreply@example.com'), ['siteowner@example.com'], connection=conn)

            return HttpResponseRedirect("/contact?submitted=True")

    else:
        form = ContactForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, "pages/contact.html", {'form': form, 'page_list': Page.objects.all(), 'submitted': submitted})

quotes/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Quote
from .forms import QuoteForm
from pages.models import Page


class QuoteList(ListView):
    model = Quote
    context_object_name = 'all_quotes'

    def get_context_data(self, **kwargs):
        context = super(QuoteList, self).get_context_data(**kwargs)
        context['page_list'] = Page.objects.all()
        return context


class QuoteView(DetailView):
    model = Quote
    context_object_name = 'quote'

    def get_context_data(self, **kwargs):
        context = super(QuoteView, self).get_context_data(**kwargs)
        context["page_list"] = Page.objects.all()
        return context


def quote_req(request):
    submitted = False

    if request.method == 'POST':
        form = QuoteForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/quote/?submitted=True')

    else:
        form = QuoteForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'quotes/quote.html', {'form': form, 'page_list': Page.objects.all(), 'submitted': submitted})

pages/templates/pages/contact.html
{% extends 'pages/page.html' %}

{% block title %}Contact Us{% endblock title %}

{% block content %}
<h1>Contact Us</h1>

{% if submitted %}
    <p class="success">Your message was submitted successfully. Thank you.</p>

{% else %}
    <form action="" method="post" novalidate>
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Submit"></td>
            </tr>
        </table>
        {% csrf_token %}
    </form>
{% endif %}
{% endblock content %}

pages/templates/pages/page.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
{% autoescape off %}
{{ content }}
{% endautoescape %}

{% block sidenav %}
{% for page in page_list %}
    <li>
        <a href="{{ page.permalink }}">{{ page.title }}</a>
    </li>
{% endfor %}
{% endblock sidenav %}

<p>
    Page last updated: {{ last_updated | date:"D d F Y"}}
</p>
{% endblock content %}

quotes/templates/quotes/quote.html
{% extends 'base.html' %}

{% block title %}Quote Request{% endblock title %}

{% block sidenav %}
    {% for page in page_list %}
        <li>
            <a href="{{ page.permalink }}">{{ page.title }}</a>
        </li>
    {% endfor %}
{% endblock sidenav %}

{% block content %}
    <h1>Quote Request</h1>

    {% if submitted %}
        <p class="success">Your quote was submitted successfully. Thank your.</p>

    {% else %}
        <form action="" enctype="multipart/form-data" method="post" novalidate>
            <table>
                {{ form.as_table }}
                <tr>
                    <td>$nbsp;</td>
                    <td><input type="submit" value="Submit"></td>
                </tr>
            </table>
            {% csrf_token %}
        </form>
    {% endif %}
{% endblock content %}

quotes/templates/quotes/quote_detail.html
{% extends 'quotes/quote.html' %}

{% block title %}All Quotes{% endblock title %}

{% block content %}
    <h1>Quote Detail</h1>

    <table class="quote">
        <tr>
            <td>ID:</td>
            <td>{{ quote.id }}</td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>{{ quote.name }}</td>
        </tr>
        <tr>
            <td>Company:</td>
            <td>{{ quote.company }}</td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>{{ quote.email }}</td>
        </tr>
        <tr>
            <td>Web Address:</td>
            <td>{{ quote.web }}</td>
        </tr>
        <tr>
            <td>ob Description</td>
            <td>{{ quote.description }}</td>
        </tr>
        <tr>
            <td>Site Status:</td>
            <td>{{ quote.get_sitestatus_display }}</td>
        </tr>
        <tr>
            <td>Priority:</td>
            <td>{{ quote.get_priority_display }}</td>
        </tr>
        <tr>
            <td>Submit Date:</td>
            <td>{{ quote.submitted | date:"m-d-y" }}</td>
        </tr>
        <tr>
            <td>Date:</td>
            <td>{{ quote.quotedate | date:"m-d-y" | default:"pending" }}</td>
        </tr>
        <tr>
            <td>Quote Price:</td>
            <td>{{ quote.quoteprice | default:"--" }}</td>
        </tr>
    </table>
    <p><a href="../show">Back to quote list</a></p>
{% endblock content %}

quotes/templates/quotes/quote_list.html
{% extends 'quotes/quote.html' %}

{% block title %}All Quotes{% endblock title %}

{% block content %}
    <h1>All Quotes</h1>

    <table style="border-collapse:collapse">
        <tr class="quotehdr">
            <th>ID</th>
            <th>Client Name</th>
            <th>Company</th>
            <th>Submitted</th>
            <th>Quoted</th>
            <th>Quote Price</th>
        </tr>
        {% for quote in all_quotes %}
            <tr class="quoterow {% cycle '' 'altrow' %}">
                <td><a href="{% url 'quote-detail' quote.id %}">{{ quote.id }}</a></td>
                <td>{{ quote.name }}</td>
                <td>{{ quote.company }}</td>
                <td>{{ quote.submitted | date:"m-d-y" }}</td>
                <td>{{ quote.quotedate | date:"m-d-y" | default:"pending" }}</td>
                <td>{{ quote.quoteprice | default:"--" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Untitled Document
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'main.css' %}" type="text/css">
</head>
<body>
    <div id="wrapper">
        <header id="header">
            <div id="logo">
                <img src="{% static 'logo.jpg' %}" alt="">
            </div>
            <div id="topbanner">
                <img src="{% static 'top_banner.png' %}" width="800" height="200" alt="">
            </div>
        </header>

        <aside id="leftsidebar">
            <nav id="nav">
                <ul>
                    {% block sidenav %}
                    {% endblock sidenav %}
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'quote-request' %}">Get a Quote</a></li>
                    <li><a href="{% url 'show-quotes' %}">Show Quotes</a></li>
                </ul>
            </nav>
        </aside>

        <section id="main">
            {% block content %}
                <h1>Welcome!</h1>
                <p>This is the site template</p>
            {% endblock content %}
            
        </section>

        <footer id="footer">
            Copyright &copy; 2019 Meadco Web Design
        </footer>
    </div>
</body>
</html>